# Generated by Django 5.0 on 2025-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
