# Generated by Django 5.0 on 2025-02-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_orderitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
