# Generated by Django 5.0 on 2024-10-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('gluten', 'Gluten'), ('lactosa', 'Lactosa'), ('soja', 'Soja'), ('frutos_secos', 'Frutos secos'), ('mariscos', 'Mariscos'), ('huevo', 'Huevo')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BurgerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('clasica', 'Clásica'), ('doble', 'Doble carne'), ('vegetariana', 'Vegetariana'), ('pollo', 'Pollo'), ('especial', 'Especial de la casa')], max_length=20, unique=True)),
            ],
        ),
    ]
