# Generated by Django 5.0 on 2024-10-13 01:17

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('precio', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', help_text='Precio del producto con soporte de moneda', max_digits=10)),
            ],
        ),
    ]
