# Generated by Django 5.0 on 2024-10-13 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='product.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='precioproducto',
            unique_together={('producto', 'precio_currency')},
        ),
    ]
