# Generated by Django 5.0 on 2024-10-22 16:51

import colorfield.fields
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
                ('imagen', models.ForeignKey(blank=True, help_text='Selecciona una imagen para esta categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='multimedia.mediafile')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='common.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción')),
                ('color', colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=25, samples=None)),
                ('imagen', models.ForeignKey(blank=True, help_text='Selecciona una imagen para esta etiqueta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='multimedia.mediafile')),
            ],
        ),
    ]
