# Generated by Django 5.0 on 2024-10-08 00:20

import django.db.models.deletion
import multimedia.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('file', models.FileField(help_text='Suba un archivo PDF.', upload_to='documents/', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Archivo de Documento',
                'verbose_name_plural': 'Archivos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Sube un fichero de imagen válido.', upload_to='media_files/', validators=[multimedia.validators.validate_image_file], verbose_name='Fichero')),
                ('title', models.CharField(blank=True, help_text='Título o descripción de la imagen.', max_length=255, null=True, verbose_name='Título')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='El usuario propietario de este archivo', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
        ),
    ]
