# Generated by Django 5.0 on 2024-10-22 16:48

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Sube una foto de perfil (opcional)', null=True, upload_to='profile_pictures/')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Ingresa tu fecha de nacimiento', null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de residencia (calle y número)', max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde vives', max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal de tu área', max_length=10, null=True)),
                ('pais', django_countries.fields.CountryField(blank=True, help_text='País de residencia', max_length=2, null=True)),
                ('suscripcion_boletin', models.BooleanField(default=False, help_text='Marca esta casilla si deseas recibir nuestro boletín de noticias')),
                ('puntos_fidelidad', models.PositiveIntegerField(blank=True, default=0, help_text='Puntos acumulados en el programa de fidelidad', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha en que te uniste a nosotros')),
                ('alergias', models.ManyToManyField(blank=True, help_text='Indica si tienes alguna alergia alimentaria', to='core.allergy')),
                ('gustos_hamburguesas', models.ManyToManyField(blank=True, help_text='Selecciona tus hamburguesas favoritas', to='core.burgertype')),
                ('user', models.OneToOneField(help_text='Usuario asociado a este perfil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
